### PR TITLE
Fix/node name

### LINKED ISSUE #137: Check for node name before sending email
Check if node name is defined before sending email to avoid sending null for name.
Current state: `Your node null - 192.168.0.26 is down.`

### PR DESCRIPTION
**Pull request by nmlinaric**
Added check if node name is defined before proceeding to sending email notification.

Resolves #137 Check for node name before sending email

### CODE REVIEW

File: src/Services/NodeUptimeNotificationService.ts [hunk 1]
```diff
@@ -103,9 +103,10 @@ export class NodeUptimeNotificationService {
                 logger.info(`Sending mail to: ${user.email} for node: ${node.id}::${node.address}`);
                 if (config.env != "dev") {
                     logger.info(`Going to send email to ${user.id}.`);
+                    const nodeName = node.name ? node.name : '';
```
Comment (morrigan) [inline src/Services/NodeUptimeNotificationService.ts:106]: Default on frontend is `Node ${node.id}` so we can use that here as well

File: src/Services/NodeUptimeNotificationService.ts [hunk 2]
```diff
@@ -103,9 +103,10 @@ export class NodeUptimeNotificationService {
                 logger.info(`Sending mail to: ${user.email} for node: ${node.id}::${node.address}`);
                 if (config.env != "dev") {
                     logger.info(`Going to send email to ${user.id}.`);
+                    const nodeName = node.name ? node.name : node.id;
```
Comment (morrigan) [inline src/Services/NodeUptimeNotificationService.ts:106]: Not only id but `Node ${node.id}` as without context it looks weird.

Also, you can use syntax `node.name || "Node ${node.id}"` :)
