### PR TITLE
Fix/node balance response

### LINKED ISSUE #81: Response when no node balance
Return current Balance: 0 when there is no updated balance in the last 24 hours.

### PR DESCRIPTION
**Pull request by nmlinaric**
Fixed response when no balance in the last 24h.
Added balance change (last 24h) for frontend.

Resolves #81 Response when no node balance.

### CODE REVIEW

File: src/Services/NodeBalanceService.ts [hunk 1]
```diff
@@ -28,10 +27,14 @@ export class NodeBalanceService {
             return {
                 currentBalance: latestRecord,
                 updatedAt: balances[balances.length - 1].updatedAt,
+                balanceChange: earliestRecord.minus(latestRecord),
                 balanceChangePerc: (latestRecord.minus(earliestRecord))
                     .div(earliestRecord).multipliedBy(100).toFixed(2) + '%'
             }
+        } else {
+            return {
+                currentBalance: 0
```
Comment (morrigan) [inline src/Services/NodeBalanceService.ts]: Return other information as well, it's easier for the frontend to handle successful responses the same way. BalanceChangePerc is then 0 and updatedAt can be time now
