### PR TITLE
Fix/mining rewards filter

### LINKED ISSUE #105: Fix mining rewards filter
Should sum mining rewards per filter (day in case of month, hour in case of day)

### PR DESCRIPTION
**Pull request by nmlinaric**
I had an enlightenment yesterday and figured out that we were using the wrong db column type (it should be NUMERIC(XX,YY) instead of BIGINT. We can change the types to NUMERIC, it supports to 1000 number length from which 500 can be decimal places (tested).

Now the SQL query is very simple and the possibly complicated logic on the backend is avoided.
The query returns the sum of rewardAmounts by the selected filter (by hour for day filter, by day for week/month/year filter).

Resolves #105 Fix mining rewards filter.

### CODE REVIEW

File: src/Migrations/20200203143917-create-minig-rewards-table.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ module.exports = {
                 type: sequelize.STRING
             },
             rewardAmount: {
-                type: sequelize.STRING
+                type: sequelize.NUMERIC(200, 100)
```
Comment (morrigan) [inline src/Migrations/20200203143917-create-minig-rewards-table.js]: We won't store decimals so don't need the second argument (scale). I think that the max FILL supply is 2B (10^12) and then extra 18 decimal points representation. So I'd put 30 or 32 to be on the safe side.

I am not expert on this one but it's probably better to have it more precise to real numbers because of calculations and storage.

File: src/Services/MiningRewardsService.ts [hunk 2]
```diff
@@ -27,16 +26,21 @@ export class MiningRewardsService {
...
+            from "MiningRewards"
+            where "nodeId" = :nodeId
+            and "updatedAt" >= now() - interval :filter
+            group by date_trunc(:period, "updatedAt")
+            order by "timePeriod" desc;`,
+            {
+                replacements: {
+                    filter: `1 ${filter}`,
+                    nodeId: nodeId,
+                    period: filter == "day" ? "hour" : "day"
```
Comment (morrigan) [inline src/Services/MiningRewardsService.ts]: Can you extract this into a function somewhere? In case we need to change it it might be good to have it in one place so all filters behave the same for the period.

Comment (nmlinaric) [reply src/Services/MiningRewardsService.ts]: I'll do, but not sure about it because Sequelize doesn't like and is very strict about things like that.

File: src/Models/MiningReward.ts [hunk 3]
```diff
@@ -14,7 +14,7 @@ export class MiningReward extends Model {
                 allowNull: false,
             },
             rewardAmount: {
-                type: DataTypes.STRING,
+                type: DataTypes.DECIMAL(32),
```
Comment (morrigan) [inline src/Models/MiningReward.ts]: NUMERIC or DECIMAL? Does it make any difference?

File: src/Utils/filterSelectQueryConfig.ts [hunk 4]
```diff
@@ -0,0 +1,12 @@
+import {QueryTypes, QueryOptionsWithType} from "sequelize";
+
+export function filtersSelectQuery(nodeId: number, filter: string): QueryOptionsWithType<QueryTypes.SELECT> {
+    return {
+        replacements: {
+            filter: `1 ${filter}`,
+            nodeId: nodeId,
+            period: filter == "day" ? "hour" : "day"
```
Comment (morrigan) [inline src/Utils/filterSelectQueryConfig.ts]: oh, I was thinking only for the `period` but it's ok I guess like this as well :)

File: src/Models/MiningReward.ts (hunk 3 above)
Comment (nmlinaric) [reply src/Models/MiningReward.ts]: Sequelize only knows about the decimal data type so it's actually transformed into numeric which is set up in the migration file.

Comment (morrigan) [reply src/Models/MiningReward.ts]: I think they are the same in behavior but both supported by postgresql so that's weird. Okay
