### PR TITLE
Fix/node balance

### LINKED ISSUE #123: Balance 0 if no report in last 24 hours
Expected:

Return last balance with 0% change. On frontend we can display to user how old is that information but we should not say it's 0.

### PR DESCRIPTION
**Pull request by nmlinaric**
Fixed the response if no node balance records in the last 24 h to return the latest node balance record outside of the last 24 h. 
Added integration test, fixed old unit test and added new unit test for the changes.

Resolves #123 Balance 0 if no report in last 24 hours.

### CODE REVIEW

File: src/Services/NodeBalanceService.ts [hunk 1]
```diff
@@ -32,12 +32,13 @@ export class NodeBalanceService {
                     .div(earliestRecord).multipliedBy(100).toFixed(2) + '%'
             }
         } else {
-            return {
-                currentBalance: 0,
-                updatedAt: moment.utc(),
-                balanceChange: 0,
-                balanceChangePerc: 0 + '%'
-            }
+            return await NodeBalance.findOne({
```
Comment (morrigan) [inline src/Services/NodeBalanceService.ts]: maybe this should be else if? and else part would stay as before if this is potentially null (no records).
Would be great if we could keep the same response structure in this one too (balance change and perc as 0).

Comment (nmlinaric) [reply src/Services/NodeBalanceService.ts]: What should we return for updatedAt when there are no records? Now or 0

Comment (morrigan) [reply src/Services/NodeBalanceService.ts]: Same as before is fine (now - moment.utc())
